### ISSUE TITLE
is any migration feature?

### ISSUE THREAD

**Issue by MahdiPishguy** [tekartik/sembast.dart#41] opened 2019-06-14 08:15 UTC
i can't find this feature on api reference, could you help me how can i have this feature?

**Comment by alextekartik** [comment] 2019-06-14 13:59
Indeed the documentation is non-existent on this. I added some notes here: https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/open.md#database-migration

**Comment by MahdiPishguy** [comment] 2019-06-14 15:36
@alextekartik 

thanks, now could you take a sample code to know how can i use that?

**Comment by Ishokov-Dzhafar** [comment] 2019-06-20 14:26
@alextekartik 
I have some code in migration method, but it didn't work. 
`Database db = await dbFactory.openDatabase( dbPath, version: 3,
      onVersionChanged: (dataBase, oldVersion, newVersion) async {
      if(oldVersion == 2) {
        print('Migration version 2');
        var store = intMapStoreFactory.store('animals');
        await dataBase.transaction((txn) async {
          var records = await store.find(txn);

          for(var item in records) {
            print('MIGRATION -> '+jsonEncode(item.value));
            await store.add(txn, item.value);
          }

          for(var item in records)
            await store.delete(txn, finder: Finder(filter: Filter.byKey(item.key)) );
        });
      }
  });`

**Comment by alextekartik** [comment] 2019-06-20 15:00
Hi @Ishokov-Dzhafar thanks for the report. Hard to tell what could be wrong. I'm not sure what you are doing here. It seems that you are re-adding all the records that already exists in a store and then deleting them, so I guess your store should be empty after opening here during the 'migration'...Are you able to isolate the issue in a unit test that you could share?

**Comment by Ishokov-Dzhafar** [comment] 2019-06-21 07:18
@alextekartik 
```
Database db = await dbFactory.openDatabase( dbPath, version: 3,
      onVersionChanged: (dataBase, oldVersion, newVersion) async {
    var store = intMapStoreFactory.store('animals');
    if(oldVersion == 1) {
      await dataBase.transaction((txn) async {
        for (var i = 1; i < 21; i++) {
          await store.add(txn, {'name': 'fish$i'});
        }
      });
    }
    if (oldVersion == 2) {
      await dataBase.transaction((txn) async {
        var records = await store.find(txn);

        for(var item in records)
          await store.delete(txn, finder: Finder(filter: Filter.byKey(item.key)) );
      });
    }
  });`

**Comment by alextekartik** [comment] 2019-06-21 07:48
This is an example of a flutter unit test that works:

```dart
import 'dart:io';

import 'package:flutter_test/flutter_test.dart' hide Finder;
import 'package:path/path.dart';
import 'package:sembast/sembast.dart';
import 'package:sembast/sembast_io.dart';

var store = intMapStoreFactory.store('animals');

Future<Database> openDatabaseV1(String path) async {
  return await databaseFactoryIo.openDatabase(path, version: 1);
}

Future<Database> openDatabaseV3(String path) async {
  return await databaseFactoryIo.openDatabase(path, version: 3,
      onVersionChanged: (dataBase, oldVersion, newVersion) async {
    // Transition from v1 => v2
    if (oldVersion == 1) {
      await dataBase.transaction((txn) async {
        for (var i = 1; i < 21; i++) {
          await store.add(txn, {'name': 'fish$i'});
        }
      });
      // Version 2 now
      oldVersion = 2;
    }
    if (oldVersion == 2) {
      // Delete all records
      await dataBase.transaction((txn) async {
        var records = await store.find(txn);

        for (var item in records) {
          await store.record(item.key).delete(txn);
        }
      });
    }
  });
}

void main() {
  test('get', () async {
    final path = join('.dart_tool', 'sembast_exp', 'issue_41.db');

    // Delete existing
    try {
      await File(path).delete();
    } catch (_) {}

    Database db;

    // open v1
    db = await openDatabaseV1(path);
    expect(db.version, 1);
    await db.close();

    // open v3
    // All the records are added and removed!
    db = await openDatabaseV3(path);
    expect(db.version, 3);

    // Should be empty!
    expect(await store.find(db), isEmpty);

    await db.close();
  });
}
```

**Comment by Ishokov-Dzhafar** [comment] 2019-06-21 09:20
@alextekartik  Your unit test work fine, but it is only unit test. Lets do my code with step by step:
<details>

<summary> There is code </summary>

```dart
import 'dart:convert';
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:path/path.dart';

import 'package:sembast/sembast_io.dart';
import 'package:sembast/sembast.dart';
import 'package:path_provider/path_provider.dart';

void main() async {

  await workWithDB();

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

var store = intMapStoreFactory.store('animals');

workWithDB() async {
  Directory documentsDirectory = await getApplicationDocumentsDirectory();
  String dbPath = join(documentsDirectory.path, 'sample.db');
  await databaseFactoryIo.openDatabase( dbPath, version: 3,
      onVersionChanged: (dataBase, oldVersion, newVersion) async {
        if(oldVersion < 2 && newVersion > 1) {
          await dataBase.transaction((txn) async {
            for (var i = 1; i < 21; i++) {
              await store.add(txn, {'name': 'fish$i'});
            }
          });
        }
        if (oldVersion < 3 && newVersion > 2) {
          await dataBase.transaction((txn) async {
            var records = await store.find(txn);

            for(var item in records)
              await store.delete(txn, finder: Finder(filter: Filter.byKey(item.key)) );
          });
        }
      });
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```
</details>

<details>

<summary> Instruction </summary>

```
1. Run with version 1,
2. Run with version 2,
3. Run with version 3 and you will see that the application is stack.
```
</details>

**Comment by alextekartik** [comment] 2019-06-21 10:27
thanks for the report. Indeed I was able to reproduce the issue in the following unit test:

```dart
import 'dart:io';

import 'package:flutter_test/flutter_test.dart' hide Finder;
import 'package:path/path.dart';
import 'package:sembast/sembast.dart';
import 'package:sembast/sembast_io.dart';

var store = intMapStoreFactory.store('animals');

Future<Database> openDatabase(String path, int version) async {
  return await databaseFactoryIo.openDatabase(path, version: version,
      onVersionChanged: (dataBase, oldVersion, newVersion) async {
    if (oldVersion < 1) {
      await dataBase.transaction((txn) async {
        for (var i = 1; i < 21; i++) {
          await store.add(txn, {'name': 'fish$i'});
        }
      });
    }
    if (oldVersion < 2 && newVersion > 1) {
      await dataBase.transaction((txn) async {
        var records = await store.find(txn);

        for (var item in records) {
          await store.delete(txn,
              finder: Finder(filter: Filter.byKey(item.key)));
        }
      });
    }
  });
}

void main() {
  test('issue41', () async {
    final path = join('.dart_tool', 'sembast_exp', 'issue_41.db');

    // Delete existing
    try {
      await File(path).delete();
    } catch (_) {}
    Database db;
    db = await openDatabase(path, 1);
    await db.close();

    db = await openDatabase(path, 2);
    await db.close();
  });
}
```

I will look into it.

**Comment by alextekartik** [comment] 2019-06-21 16:06
Should be fixed in sembast 1.16.0+1 just published. Thanks again for taking the time to reproduce the issue.

**Comment by Ishokov-Dzhafar** [comment] 2019-06-24 08:53
> Should be fixed in sembast 1.16.0+1 just published. Thanks again for taking the time to reproduce the issue.

When I do migrate from version 2 to version 3 in my example, the result file looks like:
`{"version":2,"sembast":1}`
But currently version must be 3, not 2. Can you resolve this problem?

**Comment by alextekartik** [comment] 2019-06-24 10:17
Hmmm. Can you confirm there is no `{"version":3,"sembast":1}` later in the file? Although this is poorly documented (https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/storage_format.md i just updated), like records, meta data changes are appended to the file. So the first line might not reflect the current version. But the application still see it as version 3.

**Comment by Ishokov-Dzhafar** [comment] 2019-06-24 12:53
> Hmmm. Can you confirm there is no `{"version":3,"sembast":1}` later in the file? Although this is poorly documented (https://github.com/tekartik/sembast.dart/blob/master/sembast/doc/storage_format.md i just updated), like records, meta data changes are appended to the file. So the first line might not reflect the current version. But the application still see it as version 3.

After migration to version 3, file have only `{"version":2,"sembast":1}`. After change version to 4 and run application, then method `onVersionChanged: (dataBase, oldVersion, newVersion)` run with `oldVersion = 2` and `newVersion = 4`.

**Comment by alextekartik** [comment] 2019-06-24 13:38
Sorry I cannot manage to reproduce using the latest version (1.16.0+2). Did you manage to create a unit tests so I can investigate easily?

**Comment by Ishokov-Dzhafar** [comment] 2019-06-24 14:28
> Sorry I cannot manage to reproduce using the latest version (1.16.0+2). Did you manage to create a unit tests so I can investigate easily?

I can write unit test for this issue.
<details>

<summary>Code</summary>

```dart
void main() async {

  test('get', () async {
    Directory documentsDirectory = await getApplicationDocumentsDirectory();
    final path = join(documentsDirectory.path, 'sample.db');

    // Delete existing
    try {
      await File(path).delete();
    } catch (_) {}

    Database db;

    // open v1
    db = await openDatabaseV1(path);
    expect(db.version, 1);
    await db.close();

    // open v2
    // All the records are added!
    db = await openDatabaseV2(path);
    expect(db.version, 2);

    // open v3
    // All the records are removed!
    db = await openDatabaseV3(path);
    expect(db.version, 3);

    // Should be empty!
    expect(await store.find(db), isEmpty);

    await db.close();
  });

  runApp(MyApp());
}


var store = intMapStoreFactory.store('animals');

Future<Database> openDatabaseV1(String path) async {
  return await databaseFactoryIo.openDatabase(path, version: 1);
}

Future<Database> openDatabaseV2(String path) async {
  return await databaseFactoryIo.openDatabase(path, version: 2,
      onVersionChanged: (dataBase, oldVersion, newVersion) async {
        // Transition from v1 => v2
        if (oldVersion == 1) {
          await dataBase.transaction((txn) async {
            for (var i = 1; i < 21; i++) {
              await store.add(txn, {'name': 'fish$i'});
            }
          });
        }
      });
}

Future<Database> openDatabaseV3(String path) async {
  return await databaseFactoryIo.openDatabase(path, version: 3,
      onVersionChanged: (dataBase, oldVersion, newVersion) async {
        // Transition from v2 => v3
        if (oldVersion == 2) {
          // Delete all records
          await dataBase.transaction((txn) async {
            var records = await store.find(txn);
            for (var item in records) {
              await store.record(item.key).delete(txn);
            }
          });
        }
      });
}
```

</details>

My project <b>pubspec.yaml</b> has dependencies: 
<b>sembast: ^1.16.0+2
path_provider: ^1.1.0</b>

**Comment by alextekartik** [comment] 2019-06-24 16:51
You forgot to close the database in your test. migration can only be done when the database is closed.

```dart
// open v2
// All the records are added!
db = await openDatabaseV2(path);
expect(db.version, 2);

// >>>>>> added to fix the test
await db.close();
// <<<<<<

// open v3
// All the records are removed!
db = await openDatabaseV3(path);
expect(db.version, 3);
```

**Comment by Ishokov-Dzhafar** [comment] 2019-06-25 06:40
> You forgot to close the database in your test. migration can only be done when the database is closed.
> 
> ```dart
> // open v2
> // All the records are added!
> db = await openDatabaseV2(path);
> expect(db.version, 2);
> 
> // >>>>>> added to fix the test
> await db.close();
> // <<<<<<
> 
> // open v3
> // All the records are removed!
> db = await openDatabaseV3(path);
> expect(db.version, 3);
> ```

sorry its my mistake. Now migration work fine. But I dont testing for very complicated use-case.

**Closed** 2019-06-28 15:51 UTC
